---
title: "EDA"
subtitle: "법령"
editor_options: 
  chunk_output_type: console
---

# 조항목 행수

```{r}
library(tidyverse)
library(readxl)
library(gt)
library(gtExtras)

law_EDA <- 
  read_rds("data/law_EDA.rds") 

law_EDA |> 
  count(법령명, sort = TRUE, name = "행수") |> 
  slice_max(행수, n = 10) |> 
  gt() |> 
  gt_theme_538() |> 
  fmt_integer(행수) |> 
  tab_header(
    title = md("상위 행수 20개 조항목 법령")
  )
```

## 법령구분

:::{.panel-tabset}

### 법률 {.unnumbered}

```{r}
law_lines_top <- law_EDA |> 
  group_by(법령구분) |> 
  count(법령명, 법령구분, sort = TRUE, name = "행수") 

law_lines_top |> 
  filter(법령구분 == "법률") |> 
  slice_max(행수, n = 20) |>
  pivot_wider(names_from = 법령구분, values_from = 행수, values_fill = 0) |> 
  gt() |> 
  gt_theme_538() |> 
  fmt_integer() |> 
  tab_header(
    title = md("상위 행수 20개 법률")
  )
```

### 시행령 {.unnumbered}

```{r}
law_lines_top |> 
  filter(법령구분 == "시행령") |> 
  slice_max(행수, n = 20) |>
  pivot_wider(names_from = 법령구분, values_from = 행수, values_fill = 0) |> 
  gt() |> 
  gt_theme_538() |> 
  fmt_integer() |> 
  tab_header(
    title = md("상위 행수 20개 시행령")
  )
```

### 시행규칙 {.unnumbered}

```{r}
law_lines_top |> 
  filter(법령구분 == "시행규칙") |> 
  slice_max(행수, n = 20) |>
  pivot_wider(names_from = 법령구분, values_from = 행수, values_fill = 0) |> 
  gt() |> 
  gt_theme_538() |> 
  fmt_integer() |> 
  tab_header(
    title = md("상위 행수 20개 시행규칙")
  )
```

:::


# 법령별 사무판단 건수와 행수

## 법령별 사무판단 건수

```{r}
law_EDA |>
  group_by(법령명, 사무_판단) |>
  summarise(건수 = n()) |>
  ungroup() |> 
  pivot_wider(names_from = 사무_판단, values_from = 건수, values_fill = 0) |>
  mutate(합계 = `0` + `1`) |>
  mutate(비율 = `1` / 합계 ) |> 
  rename("사무없음" =`0`,  "사무있음" = `1`) |> 
  mutate(사무여부 = if_else(사무있음 > 0, "사무있음", "사무없음")) |> 
  count(사무여부, name = "법령건수") |> 
  mutate(비율 = 법령건수 / sum(법령건수)) |> 
  janitor::adorn_totals(name = "합계") |> 
  gt() |> 
  cols_align("center") |> 
  fmt_integer(법령건수) |> 
  fmt_percent(비율, decimals = 1) |> 
  gt_theme_538() |> 
  tab_header(
    title = md("법령 기준 사무판단 건수")
  ) 
```


:::{.panel-tabset}

### 표 {.unnumbered}

```{r}
law_EDA |>
  group_by(법령명, 사무_판단) |>
  summarise(건수 = n()) |>
  ungroup() |> 
  pivot_wider(names_from = 사무_판단, values_from = 건수, values_fill = 0) |>
  mutate(합계 = `0` + `1`) |> 
  arrange(desc(`1`)) |> 
  rename("사무없음" =`0`,  "사무있음" = `1`) |>
  mutate(비율 = 사무있음/합계) |> 
  slice(1:20) |> 
  gt() |>
  cols_align("center") |>
  fmt_integer(c(사무없음, 사무있음, 합계)) |>
  fmt_percent(비율, decimals = 1) |> 
  gt_theme_538() |>
  tab_header(
    title = md("법령 기준 사무판단 상위 20개 법령")
  )
```

### 그래프 {.unnumbered}

```{r}
library(ggrepel)

law_EDA_ev <- law_EDA |>
  group_by(법령명, 사무_판단) |>
  summarise(건수 = n()) |>
  ungroup() |> 
  pivot_wider(names_from = 사무_판단, values_from = 건수, values_fill = 0) |>
  mutate(합계 = `0` + `1`) |> 
  arrange(desc(`1`)) |> 
  rename("사무없음" =`0`,  "사무있음" = `1`) |>
  mutate(is_y_ev = 사무있음 > quantile(사무있음, 0.995) | 사무있음 < quantile(사무있음, 0.005)) |> 
    mutate(is_x_ev = 합계 > quantile(합계, 0.995) | 합계 < quantile(합계, 0.005))  

law_EDA_ev |> 
  ggplot(aes(x = 합계, y = 사무있음 )) +
    geom_point() +
    labs(x = "조항호 수", y = "사무판단 건수") +
    scale_x_continuous(labels = scales::comma) +
    theme_minimal() +
    geom_text_repel(data = law_EDA_ev |> filter(is_y_ev), aes(label = 법령명), vjust = -1) +
    geom_text_repel(data = law_EDA_ev |> filter(is_x_ev), aes(label = 법령명), vjust = -1)
```

:::


## 행수분포와 사무판단

```{r}
law_raw <- read_excel("data/(230410)최종결과표(통합본).xlsx", skip = 0)

law_tbl <- law_raw |>
  janitor::clean_names(ascii = FALSE) |> 
  mutate(사무_판단 = ifelse(is.na(사무_판단), 0, 사무_판단)) |> 
  mutate(사무유형 = str_remove(사무유형, "\r\n")) |>
  # 사무유형: 국가, 시도, 공동, ...
  mutate(사무유형 = case_when(사무유형 == "국가시도" ~ "국가-시도",
                              사무유형 == "정부" ~ "국가",
                              사무유형 == "공동" ~ "국가-시도",
                              is.na(사무유형) ~ "없음",
                              TRUE ~ 사무유형))  


law_tbl |> 
  group_by(법령명) |> 
  summarise(사무건수 = sum(사무_판단),
            행수 = n()) |> 
  mutate(사무판단 = ifelse(사무건수 == 0, "사무없음", "사무있음")) |> 
  ggplot(aes(x = 행수, fill = 사무판단)) +
    geom_density(alpha = 0.7) +
    theme(legend.position = "bottom") +
    scale_x_sqrt() 
```

## 수행주체

### 조문 기준

```{r}
library(gtExtras)

law_tbl |>
  mutate(중앙지자체 = case_when(사무유형 %in% c("국가") ~ "중앙정부",
                                사무유형 %in% c("시도", "시도-시군구", "시군구") ~ "지자체",
                                TRUE ~ "공동")) |>
  filter(사무유형 != "없음") |> 
  count(중앙지자체, 사무유형, name = "건수") |>
  mutate(비율 = 건수 / sum(건수)) |> 
  gt(groupname_col = "중앙지자체",
     rowname_col   = "사무유형"  ) |> 
  fmt_percent(비율, decimals = 1) |>
  fmt_integer(건수) |>
  grand_summary_rows(
    fns = list(
      "합계" = ~sum(.)),
    columns = c("건수"),
    formatter = fmt_integer
  ) |> 
  grand_summary_rows(
    fns = list(
      "합계" = ~sum(.)),
    columns = c("비율"),
    formatter = fmt_percent,
    decimals = 0
  ) |> 
  gt_theme_538()
```

### 법령 기준

:::{.panel-tabset}

#### 표 {.unnumbered}


```{r}
law_tbl |>
  mutate(중앙지자체 = case_when(사무유형 %in% c("국가") ~ "중앙정부",
                                사무유형 %in% c("시도", "시도-시군구", "시군구") ~ "지자체",
                                사무유형 == "없음" ~ "없음",
                                TRUE ~ "공동")) |>  
  # filter(사무유형 != "없음") |>
  group_by(법령명) |>
  count(중앙지자체, 사무유형) |> 
  ungroup() |> 
  count(중앙지자체, 사무유형, name = "법령건수", sort = TRUE) |> 
mutate(비율 = 법령건수 / sum(법령건수)) |> 
  gt(groupname_col = "중앙지자체",
     rowname_col   = "사무유형"  ) |> 
  fmt_percent(비율, decimals = 1) |>
  fmt_integer(법령건수) |>
  grand_summary_rows(
    fns = list(
      "합계" = ~sum(.)),
    columns = c("법령건수"),
    formatter = fmt_integer
  ) |> 
  grand_summary_rows(
    fns = list(
      "합계" = ~sum(.)),
    columns = c("비율"),
    formatter = fmt_percent,
    decimals = 0
  ) |> 
  gt_theme_538()  
```

#### 그래프 {.unnumbered}

[Venn diagram with ggVennDiagram](https://r-charts.com/part-whole/ggvenndiagram/)

```{r}
library(ggVennDiagram)


affairs_type <- law_tbl |>
  filter(사무유형 != "없음") |>
  group_by(법령명) |>
  count(사무유형) |>
  arrange(법령명, 사무유형) |>
  ungroup() |>
  separate(사무유형, into = c("사무1", "사무2", "사무3"), sep = "-") |>
  mutate(번호 = row_number()) |> 
  mutate(사무1 = str_glue("{사무1}_{번호}"),
         사무2 = str_glue("{사무2}_{번호}"),
         사무3 = str_glue("{사무3}_{번호}")) |> 
  select(-법령명, -n, -번호) |> 
  pivot_longer(사무1:사무3, names_to = "사무구분", values_to = "사무") |> 
  filter(!str_detect(사무, "^NA")) |> 
  mutate(집합 = case_when(str_detect(사무, "국가") ~ "국가",
                          str_detect(사무, "시도") ~ "시도",
                          str_detect(사무, "시군구") ~ "시군구",
                          TRUE ~ "기타")) |> 
  mutate(원소 = str_extract(사무, "\\d{1,5}"))

    
korea_type <- affairs_type |> 
  filter(집합 == "국가") |> 
  pull(원소) |> 
  unlist()

sido_type <- affairs_type |> 
  filter(집합 == "시도") |> 
  pull(원소) |> 
  unlist()

sgg_type <- affairs_type |> 
  filter(집합 == "시군구") |> 
  pull(원소) |> 
  unlist()

ggVennDiagram(list(국가 = korea_type, 시도 = sido_type, 시군구 = sgg_type),
              category.names = c("국가",
                                 "시도",
                                 "구시군"),
               label_alpha = 0,
               color = 1, lwd = 0.7) +
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  theme(legend.position = "none")

```

:::

### 국가사무 유형


```{r}
law_tbl |>
  filter(사무유형 != "없음") |>
  group_by(법령명) |>
  count(사무유형) |>
  arrange(법령명, 사무유형) |> 
  summarise(사무패턴 = str_c(사무유형, collapse = "; ")) |> 
  count(사무패턴, name = "법령건수", sort = TRUE) |> 
  gt() |> 
  fmt_integer(법령건수) |> 
  grand_summary_rows(
    fns = list(
      "합계" = ~sum(.)),
    columns = c("법령건수"),
    formatter = fmt_integer
  ) |> 
  gt_theme_538()
  
```


# 법령

법령은 법률 + 시행령 + 시행규칙 + ~~행정규칙~~ 으로 구성된다.

```{r}
law_type <- law_tbl |>
  group_by(법령명, 법령_구분) |>
  summarise(조문수 = n()) |> 
  ungroup() |>
  mutate(법령구분 = case_when(
    str_detect(법령명, "법률$") ~ "법률",
    str_detect(법령명, "시행령$") ~ "시행령",
    str_detect(법령명, "시행규칙$") ~ "시행규칙",
    TRUE ~ 법령명
  )) 


law_set <- read_excel("data/법령정보.xlsx", sheet = '법령목록') |> 
  janitor::clean_names(ascii = FALSE) |> 
  rename(법시시 = 법률_시행령_시행규칙_기타구분)

law_type_set <- law_type |>
  # mutate(법령명 = str_extract(법령명, "[0-9가-힣]+"))
  left_join(law_set |> select(법령명, 법종구분코드명, 법시시), by = "법령명") |> 
  mutate(법시시 = case_when(
    str_detect(법령명, "법률$") ~ "법률",
    str_detect(법령명, "시행령$") ~ "시행령",
    str_detect(법령명, "시행규칙$") ~ "시행규칙",
    TRUE ~ 법시시
  )) |> 
  mutate(법령_구분 = as.character(법령_구분)) |> 
  mutate(법령구분 = case_when(
    법령_구분 == "1" ~ "법률",
    법령_구분 == "2" ~ "시행령",
    법령_구분 == "3" ~ "시행규칙",
    TRUE ~ 법령_구분
  )) 

law_type_set |> 
  count(법령구분, 법시시, name = "조문수", sort = TRUE) |>
  pivot_wider(names_from = 법시시, values_from = 조문수, values_fill = 0) |> 
  relocate(법률, .after = 법령구분) |>
  mutate(법령구분 = ifelse(is.na(법령구분), "결측", 법령구분)) |> 
  mutate(법령구분 = factor(법령구분, levels = c("법률", "시행령", "시행규칙", "결측"))) |>
  arrange(법령구분) |>
  gt() |>
  gtExtras::gt_theme_538()

```


## 오분류 법령

```{r}
law_type_set |> 
  filter(법령구분 != 법시시) |> 
  select(-조문수) |> 
  gt()
```

