---
title: "Y 교차분석"
editor_options: 
  chunk_output_type: console
---

# 데이터

```{r}
library(tidyverse)
library(readxl)
library(gt)
library(gtExtras)


# 사무판단
law_raw <- read_excel("data/(230410)최종결과표(통합본).xlsx", skip = 0)

law_tbl <- law_raw |>
  janitor::clean_names(ascii = FALSE) |> 
  mutate(사무_판단 = ifelse(is.na(사무_판단), 0, 사무_판단)) |> 
  mutate(사무유형 = str_remove(사무유형, "\r\n")) |>
  # 사무유형: 국가, 시도, 공동, ...
  mutate(사무유형 = case_when(사무유형 == "국가시도" ~ "국가-시도",
                              사무유형 == "정부" ~ "국가",
                              사무유형 == "공동" ~ "국가-시도",
                              is.na(사무유형) ~ "없음",
                              TRUE ~ 사무유형))  |> 
  rename(부처명 = 소관_부처명)

## 법률, 시행령, 시행규칙
## 법령_구분 : 데이터 전처리 (정제작업, 오분류, 결측값)
law_set <- read_excel("data/법령정보.xlsx", sheet = '법령목록') |> 
  janitor::clean_names(ascii = FALSE) |> 
  rename(법시시 = 법률_시행령_시행규칙_기타구분)


law_type <- law_tbl |> 
  group_by(법령명, 법령_구분) |>
  summarise(조항수 = n()) |>
  ungroup() |> 
  mutate(법령_구분 = as.character(법령_구분)) |> 
  fill(법령_구분, .direction = "down") |>
  mutate(법령구분 = case_when(법령_구분 == "1" ~ "법률",
                              법령_구분 == "2" ~ "시행령",
                              법령_구분 == "3" ~ "시행규칙",
                              TRUE ~ 법령_구분)) |> 
  left_join(law_set |> select(법령명, 법시시) |> filter(법시시 != "NA"), by = "법령명") |>
  mutate(법시시 = if_else(is.na(법시시) | 법시시 == "기타", 법령구분, 법시시)) |>
  mutate(법령구분 = if_else(법령구분 == "법시시", 법령구분, 법시시)) |> 
  select(법령명, 법령구분 = 법시시)

law_type |> 
  count(법령구분, name = "법령수")

# # A tibble: 3 × 4
#   법령구분  법률 시행규칙 시행령
#   <chr>    <int>    <int>  <int>
# 1 법률      1451       NA     NA
# 2 시행규칙    NA     1217     NA
# 3 시행령      NA       NA   1670

```  


# EDA

## 법령별 사무판단 비율

```{r}
law_eda <- left_join(law_tbl, law_type, by = "법령명")

law_eda |>
  group_by(법령명, 법령구분, 사무_판단) |> 
  summarise(조항수 = n()) |> 
  ungroup() |> 
  count(법령구분, 사무_판단) |> 
  pivot_wider(names_from = 사무_판단, values_from = n) |> 
  rename(사무_없음 = `0`, 사무_있음 = `1`) |>
  mutate(합계 = 사무_없음 + 사무_있음) |>
  mutate(사무비율 = 사무_있음 / (사무_없음 + 사무_있음)) |> 
  relocate(사무_있음, .after = 법령구분) |>
  gt() |> 
  cols_align("center") |> 
  fmt_integer(c(사무_없음, 사무_있음, 합계)) |> 
  fmt_percent(사무비율, decimals = 1) |>
  grand_summary_rows(columns = c(사무_있음, 사무_없음, 합계), 
                     fns = list(합계 = ~sum(.)),
                     fmt = ~fmt_integer(.)) |> 
  grand_summary_rows(columns = c(사무비율), 
                     fns = list(합계 = ~sum(사무_있음) / sum(합계)),
                     fmt = ~fmt_percent(., decimals = 1)) |> 
  tab_header(title = md("**법령별 사무판단 비율**")) |>
  gt_theme_538() |> 
  cols_label(법령구분 = md("**법령구분**"),
             사무_있음 = md("**있음**"),
             사무_없음 = md("**없음**"),
             합계 = md("**합계**"),
             사무비율 = md("**사무비율**")) |> 
  tab_spanner(label = md("**사무판단**"), 
              columns = c(사무_있음, 사무_없음))
  
```



## 소관부처 갯수별 사무판단

```{r}
law_dept_no <- law_eda |> 
  select(부처명, 법령명) |> 
  # mutate(부처명 = str_remove(부처명, "\\r\\n|\\s+")) |>
  # mutate(부처명 = str_remove(부처명, " ")) |>
  mutate(소관부처 = str_split(부처명, ",")) |> 
  unnest(소관부처) |> 
  group_by(법령명) |> 
  summarise(부처수 = n_distinct(소관부처))  |> 
  arrange(desc(부처수))

law_eda |> 
  left_join(law_dept_no, "법령명") |> 
  group_by(법령명, 부처수, 사무_판단) |>
  summarise(조항수 = n()) |>
  ungroup() |>
  count(부처수, 사무_판단) |> 
  pivot_wider(names_from = 사무_판단, values_from = n) |> 
  rename(사무_없음 = `0`, 사무_있음 = `1`) |>
  mutate(합계 = 사무_없음 + 사무_있음) |>
  mutate(사무비율 = 사무_있음 / (사무_없음 + 사무_있음)) |> 
  relocate(사무_있음, .after = 부처수) |> 
  gt() |> 
  cols_align("center") |> 
  fmt_integer(c(사무_없음, 사무_있음, 합계)) |> 
  fmt_percent(사무비율, decimals = 1) |>
  grand_summary_rows(columns = c(사무_있음, 사무_없음, 합계), 
                     fns = list(합계 = ~sum(.)),
                     fmt = ~fmt_integer(.)) |> 
  grand_summary_rows(columns = c(사무비율), 
                     fns = list(합계 = ~sum(사무_있음) / sum(합계)),
                     fmt = ~fmt_percent(., decimals = 1)) |> 
  tab_header(title = md("**법령별 부처수 사무판단 비율**")) |>
  gt_theme_538() |> 
  cols_label(부처수 = md("**부처수**"),
             사무_있음 = md("**있음**"),
             사무_없음 = md("**없음**"),
             합계 = md("**합계**"),
             사무비율 = md("**사무비율**")) |> 
  tab_spanner(label = md("**사무판단**"), 
              columns = c(사무_있음, 사무_없음))

```


## 소관부처별 사무판단

```{r}
law_dept <- law_eda |> 
  mutate(부처명 = str_remove(부처명, "\\r\\n|\\s+")) |>
  # mutate(부처명 = str_remove(부처명, " ")) |>
  count(부처명) |> 
  mutate(소관부처 = str_split(부처명, ",")) |> 
  unnest(소관부처) |> 
  count(소관부처, sort = TRUE) |> 
  mutate(부처청 = case_when(
    str_detect(소관부처, "부$") ~ "부",
    str_detect(소관부처, "(처$)|(청$)") ~ "처청",
    str_detect(소관부처, "위$") ~ "위",
    str_detect(소관부처, "회$") ~ "회",
    str_detect(소관부처, "대통령실|국가안보실|국무조정실|국무총리비서실|국가정보원") ~ "대통령총리",
    TRUE ~ "기타"
  )) |>
  count(부처청, 부처명 = 소관부처) |> 
  select(-n)

law_eda |> 
  left_join(law_dept, by = "부처명") |> 
  group_by(법령명, 부처청, 사무_판단) |>
  summarise(조항수 = n()) |> 
  ungroup() |>
  # filter(is.na(부처청))
  count(부처청, 사무_판단) |> 
  pivot_wider(names_from = 사무_판단, values_from = n) 

law_eda |> 
  filter(str_detect(법령명, "세월호")) |> 
  count(부처명)
  
```
